### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by heyadityak** [rvsingh31/Project-Repository#1]
I tried to connect to the provided database file (`travel.mdf`), & it throws the following error : 

   ```

An attempt to attach an auto-named database for file C:\Users\Ravinder Singh\Source\Repos\Project-Repository\WebApplication1\WebApplication2\App_Data\travel.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.

   ```

Please check this issue.

P.S. - The project's UI is good & I am looking forward to test the project deeper... 😄

**Comment by heyadityak** [comment]
Also, rename the `index.aspx` to `default.aspx`. Coz, in ASP.NET, `default.aspx` equals `index.php` in PHP. i.e. `default.aspx` opens, if the website's URL is only typed. If `index.aspx` is used, IIS throws **error `404`**. @rvsingh31

**Comment by rvsingh31** [comment]
The default file thing i know.. I thought of making it in the last min.. Thanks for the reminder and the database connection issue is quite a thing which i dont know

**Comment by rvsingh31** [comment]
I ll find it out and let u know

**Comment by heyadityak** [comment]
I got the Solution ! Just change the `ConnectionString` in your `Web.config` as follows : 

`AttachDbFilename=|DataDirectory|\travel.mdf`

**Comment by heyadityak** [comment]
Atleast commit the changes I have said... 😞

**Comment by rvsingh31** [comment]
will do the necessary changes .don't u worry!
